# Generated by Django 5.2.8 on 2025-11-13 22:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id_caso', models.AutoField(db_column='Id_Caso', primary_key=True, serialize=False)),
                ('tipo_fuero', models.CharField(blank=True, db_column='Tipo_Fuero', max_length=100, null=True)),
                ('diagnostico', models.TextField(blank=True, db_column='Diagnostico', null=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True, db_column='Fecha_Inicio')),
                ('estado', models.CharField(db_column='Estado', default='Abierto', max_length=50)),
                ('responsable', models.CharField(blank=True, db_column='Responsable', max_length=150, null=True)),
                ('fecha_cierre', models.DateField(blank=True, db_column='Fecha_Cierre', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'db_table': 'Caso',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(db_column='Id_Empleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('cargo', models.CharField(blank=True, db_column='Cargo', max_length=100, null=True)),
                ('division', models.CharField(blank=True, db_column='Division', max_length=100, null=True)),
                ('area', models.CharField(blank=True, db_column='Area', max_length=100, null=True)),
                ('supervisor', models.CharField(blank=True, db_column='Supervisor', max_length=150, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='Fecha_Nacimiento', null=True)),
                ('fecha_ingreso', models.DateField(blank=True, db_column='Fecha_Ingreso', null=True)),
                ('correo', models.EmailField(blank=True, db_column='Correo', max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=50, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', default='Activo', max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados/fotos/')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='Id_Rol', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=100)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Rol',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(db_column='Id_Alerta', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=150, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=100, null=True)),
                ('fecha_generada', models.DateField(auto_now_add=True, db_column='Fecha_Generada')),
                ('fecha_envio', models.DateField(blank=True, db_column='Fecha_Envio', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='Fecha_Vencimiento', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', default='Pendiente', max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('caso', models.ForeignKey(db_column='Id_Caso', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.caso')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'Alerta',
                'ordering': ['-fecha_generada'],
            },
        ),
        migrations.CreateModel(
            name='CasoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.ForeignKey(db_column='Id_Caso', on_delete=django.db.models.deletion.CASCADE, to='api.caso')),
            ],
            options={
                'db_table': 'Caso_Reporte',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(db_column='Id_Documento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=150, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=100, null=True)),
                ('fecha_carga', models.DateField(auto_now_add=True, db_column='Fecha_Carga')),
                ('fecha_modificacion', models.DateField(auto_now=True, db_column='Fecha_Modificacion')),
                ('usuario_creador', models.CharField(blank=True, db_column='Usuario_Creador', max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('ruta', models.TextField(blank=True, db_column='Ruta', null=True)),
                ('extension', models.CharField(blank=True, db_column='Extension', max_length=20, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('caso', models.ForeignKey(db_column='Id_Caso', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.caso')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'Documento',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.AddField(
            model_name='caso',
            name='empleado',
            field=models.ForeignKey(db_column='Id_Empleado', on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='api.empleado'),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(db_column='Id_Reporte', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=150, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=100, null=True)),
                ('formato', models.CharField(blank=True, db_column='Formato', max_length=50, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', default='Pendiente', max_length=50, null=True)),
                ('casos', models.ManyToManyField(related_name='reportes', through='api.CasoReporte', to='api.caso')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'Reporte',
            },
        ),
        migrations.AddField(
            model_name='casoreporte',
            name='reporte',
            field=models.ForeignKey(db_column='Id_Reporte', on_delete=django.db.models.deletion.CASCADE, to='api.reporte'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(db_column='Id_Usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150)),
                ('contrasena', models.CharField(blank=True, db_column='Contrasena', max_length=255)),
                ('correo', models.EmailField(db_column='Correo', max_length=150, unique=True)),
                ('estado', models.CharField(db_column='Estado', default='Activo', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(db_column='Rol', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='api.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
                'ordering': ['nombre'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(db_column='Id_Seguimiento', primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True, db_column='Fecha')),
                ('usuario_responsable', models.CharField(blank=True, db_column='Usuario_Responsable', max_length=150, null=True)),
                ('accion_realizada', models.TextField(blank=True, db_column='Accion_Realizada', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('caso', models.ForeignKey(db_column='Id_Caso', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='api.caso')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'db_table': 'Seguimiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TokenVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('operacion', models.CharField(max_length=100)),
                ('datos', models.JSONField(default=dict)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificación de Token',
                'verbose_name_plural': 'Verificaciones de Tokens',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='casoreporte',
            unique_together={('caso', 'reporte')},
        ),
    ]
