# Generated by Django 5.2.8 on 2025-11-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expiringtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ciudad',
            field=models.CharField(blank=True, db_column='Ciudad', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_documento',
            field=models.CharField(blank=True, db_column='Numero_Documento', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('NIT', 'NIT')], db_column='Tipo_Documento', max_length=20, null=True),
        ),
    ]
