# Generated by Django 5.2.8 on 2025-11-21 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_empleado_documento_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='responsable',
            field=models.ForeignKey(blank=True, db_column='Responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
