# Generated by Django 5.2.8 on 2025-11-24 00:27

from django.db import migrations, models


def convertir_estados_a_minusculas(apps, schema_editor):
    """Convierte los estados existentes a minúsculas para cumplir con el constraint"""
    Caso = apps.get_model('api', 'Caso')
    
    # Mapeo de estados antiguos a nuevos (en minúsculas)
    mapeo_estados = {
        'Pendiente': 'pendiente',
        'pendiente': 'pendiente',
        'Abierto': 'abierto',
        'abierto': 'abierto',
        'Cerrado': 'cerrado',
        'cerrado': 'cerrado',
    }
    
    # Actualizar todos los casos
    for caso in Caso.objects.all():
        estado_actual = caso.estado
        if estado_actual:
            estado_nuevo = mapeo_estados.get(estado_actual, 'abierto')  # Default a 'abierto' si no coincide
            if estado_actual != estado_nuevo:
                caso.estado = estado_nuevo
                caso.save(update_fields=['estado'])


def revertir_estados(apps, schema_editor):
    """Función de reversión (opcional)"""
    # No es necesario revertir ya que los datos se mantienen
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_change_caso_responsable_to_fk'),
    ]

    operations = [
        # Primero convertir los datos existentes
        migrations.RunPython(convertir_estados_a_minusculas, revertir_estados),
        # Luego actualizar el campo con las choices
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('abierto', 'Abierto'), ('cerrado', 'Cerrado')], db_column='Estado', default='abierto', max_length=50),
        ),
    ]
