# Generated by Django 5.2.8 on 2025-11-24 01:47

from django.db import migrations, models


def convertir_estados_alerta_a_minusculas(apps, schema_editor):
    """Convierte los estados existentes de alertas a minúsculas para cumplir con el constraint"""
    Alerta = apps.get_model('api', 'Alerta')
    
    # Mapeo de estados antiguos a nuevos (en minúsculas)
    mapeo_estados = {
        'Pendiente': 'pendiente',
        'pendiente': 'pendiente',
        'Enviada': 'enviada',
        'enviada': 'enviada',
        'Vencida': 'vencida',
        'vencida': 'vencida',
    }
    
    # Actualizar todas las alertas
    for alerta in Alerta.objects.all():
        estado_actual = alerta.estado
        if estado_actual:
            estado_nuevo = mapeo_estados.get(estado_actual, 'pendiente')  # Default a 'pendiente' si no coincide
            if estado_actual != estado_nuevo:
                alerta.estado = estado_nuevo
                alerta.save(update_fields=['estado'])


def revertir_estados_alerta(apps, schema_editor):
    """Función de reversión (opcional)"""
    # No es necesario revertir ya que los datos se mantienen
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_update_caso_estado_choices'),
    ]

    operations = [
        # Primero convertir los datos existentes
        migrations.RunPython(convertir_estados_alerta_a_minusculas, revertir_estados_alerta),
        # Luego actualizar el campo con las choices
        migrations.AlterField(
            model_name='alerta',
            name='estado',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('vencida', 'Vencida')], db_column='Estado', default='pendiente', max_length=50, null=True),
        ),
    ]
