# Generated by Django 5.2.8 on 2025-11-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_update_alerta_estado_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, db_column='Area', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ciudad',
            field=models.CharField(blank=True, db_column='Ciudad', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, db_column='Division', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experiencia',
            field=models.TextField(blank=True, db_column='Experiencia', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_ingreso',
            field=models.DateField(blank=True, db_column='Fecha_Ingreso', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='puesto',
            field=models.CharField(blank=True, db_column='Puesto', max_length=150, null=True),
        ),
    ]
