# Generated by Django 5.2.8 on 2025-11-24 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='empleado',
            field=models.ForeignKey(blank=True, db_column='Id_Empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='api.empleado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, db_column='Usuario_Creador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id_carpeta', models.AutoField(db_column='Id_Carpeta', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150)),
                ('fecha_creacion', models.DateField(auto_now_add=True, db_column='Fecha_Creacion')),
                ('empleado', models.ForeignKey(db_column='Id_Empleado', on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='api.empleado')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'db_table': 'Carpeta',
                'ordering': ['-fecha_creacion', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='carpeta',
            field=models.ForeignKey(blank=True, db_column='Id_Carpeta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='api.carpeta'),
        ),
    ]
