# Generated by Django 5.2.8 on 2025-11-24 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_documento_empleado_alter_documento_usuario_creador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='caso',
            field=models.ForeignKey(blank=True, db_column='Id_Caso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.caso'),
        ),
    ]
